HMS/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LogoutView
from django.conf.urls import url, include
from django.contrib import admin
from .views import (
    home_page,
    register_page,
    login_page,
)
from search.views import search

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page, name='home'),
    url(r'^register/$', register_page, name='register'),
    url(r'^login/$', login_page, name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^doctor/', include('doctor.urls', namespace='doctor')),
    url(r'^patient/', include('patient.urls', namespace='patient')),
    url(r'^messages/', include('chat.urls', namespace='chat')),
    url(r'^search/$', search, name='search'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # necessary if you  want to serves media files locally
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.conf.urls import url
from .views import (
    create_message,
    delete_msg,
    message_view,
)

app_name = "chat"

urlpatterns = [
    url(r'^new/$', create_message, name='create_message'),
    url(r'^delete/(?P<msg_pk>\d+)/$', delete_msg, name='delete_msg'),
    url(r'^messages/(?P<patient_pk>\d+)/$', message_view, name='message_view'),
]

# (?P<pk>\d+)
# (?P<slug>[\w-]+)

doctor/urls.py
from django.conf.urls import url
from .views import (
    doctor_home,
    appointments,
    preview,
    patient_list,
    update_profile,
    respond,
    view_profile,
    create_msg,
    create_appointment,
    download_report,
    GeneratePDF,
    delete_appointment,
    generate_report,
)

app_name = "doctor"

urlpatterns = [
    url(r'^appointments/(?P<doctor_pk>\d+)/(?P<slug>[\w-]+)/$', appointments, name='appointments'),
    url(r'^info/(?P<pk>\d+)/$', preview, name='doctor_preview'),
    url(r'^patients/$', patient_list, name='patient_list'),
    url(r'^update/$', update_profile, name='update'),
    url(r'^respond/(?P<ap_pk>\d+)/$', respond, name='respond'),
    url(r'^send/$', create_msg, name='create_msg'),
    url(r'^profile/$', view_profile, name='view_profile'),
    url(r'^create-appointment/$', create_appointment, name='create_appointment'),
    url(r'^download-report/(?P<ap_pk>\d+)/$', download_report, name='download_report'),
    url(r'^pdf/(?P<ap_pk>\d+)/$', GeneratePDF.as_view(), name='GeneratePDF'),
    url(r'^delete/(?P<ap_pk>\d+)/$', delete_appointment, name='delete_appointment'),
    url(r'^report/(?P<ap_pk>\d+)/$', generate_report, name='generate_report'),
]

# (?P<pk>\d+)
# (?P<slug>[\w-]+)

patient/urls.py
from django.conf.urls import url
from .views import patient_account, update_profile, patient_appointments, message_view, doctor_list

app_name = "patient"

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', patient_account, name='patient_account'),
    url(r'^update/$', update_profile, name='update'),
    url(r'^appointments/(?P<status>[\w-]+)/$', patient_appointments, name='patient_appointments'),
    url(r'^messages/(?P<doctor_pk>\d+)/$', message_view, name='messages'),
    url(r'^doctor-list/$', doctor_list, name='doctor_list'),
]

appointments/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.conf import settings
from django.db.models import Q
from django.utils import timezone

from patient.models import Patient
from doctor.models import Doctor
from HMS.utils import unique_token_no_generator

User = settings.AUTH_USER_MODEL


class AppointmentManagerQuerySet(models.query.QuerySet):
	def new(self):
		return self.filter(approved=False, disapproved=False, pending=False, done=False)

	def not_new(self):
		lookups = (Q(approved=True) |
				   Q(disapproved=True) |
				   Q(pending=True) |
				   Q(done=True))
		return self.filter(lookups)


class AppointmentManager(models.Manager):
	def get_queryset(self):
		return AppointmentManagerQuerySet(self.model, using=self._db)

	def new(self):
		return self.get_queryset().new()

	def not_new(self):
		return self.get_queryset().not_new()


class Appointment(models.Model):
	patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True, blank=True)
	doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, null=True, blank=True)

	msg_patient = models.TextField(null=True, blank=True)
	msg_doctor = models.TextField(null=True, blank=True)

	approved = models.BooleanField(default=False)
	disapproved = models.BooleanField(default=False)
	pending = models.BooleanField(default=False)
	done = models.BooleanField(default=False)
	location = models.CharField(max_length=200, null=True, blank=True)

	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	appointment_date = models.DateField(null=True, blank=True)
	appointment_time = models.TimeField(null=True, blank=True)

	diseases = models.CharField(max_length=300, null=True, blank=True)
	token_no = models.CharField(max_length=55, null=True, blank=True)
	report_generated = models.BooleanField(default=False)
	report = models.FileField(upload_to='reports', null=True, blank=True, verbose_name=' ')

	objects = AppointmentManager()

	def __str__(self):
		return str(self.doctor.full_name) + ' | ' + str(self.patient.full_name)

	def status(self):
		if self.approved:
			return "Approved"
		if self.disapproved:
			return "Disapproved"
		if self.pending:
			return "Pending"
		if self.done:
			return "Done"
		else:
			return "New"

	class Meta:
		ordering = ['-updated', '-created']


def pre_save_token_no(sender, instance, *args, **kwargs):
	if not instance.token_no:
		instance.token_no = unique_token_no_generator(instance)


pre_save.connect(pre_save_token_no, sender=Appointment)

appointments/forms.py
from django import forms
from .models import Appointment
from django.contrib.auth import authenticate, login, get_user_model
User = get_user_model()


class AppointmentRespondForm(forms.ModelForm):
    location = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Location'}
    ), label='')

    approved = forms.BooleanField(widget=forms.CheckboxInput(attrs={'checked': 'True', 'class': 'hide_this', 'style': 'display:none'}), label='')
    pending = forms.BooleanField(widget=forms.CheckboxInput(attrs={'checked': 'False', 'class': 'hide_this', 'style': 'display:none'}), label='')

    class Meta:
        model = Appointment
        # fields = ('appointment_date', 'appointment_time', 'location')
        fields = ('appointment_date', 'appointment_time', 'location', 'approved', 'pending')

        widgets = {
            'appointment_date': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'yyy-mm-dd', 'type': 'date'}),
            'appointment_time': forms.TimeInput(attrs={'class': 'form-control', 'placeholder': 'hr:min', 'type': 'time'}),
            # 'location': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Location'}),
            # 'msg_doctor': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter Message'},),
        }


class UploadReportForm(forms.ModelForm):
    # report = forms.FileField(widget=forms.FileField())

    class Meta:
        model = Appointment
        fields = ('report', )

appointments/views.py
from django.shortcuts import render

doctor/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponse
from django.views.generic import ListView, DetailView, View
from django.shortcuts import render, get_object_or_404, redirect
from accounts.forms import UpdateProfileForm
from appointments.forms import AppointmentRespondForm, UploadReportForm
from appointments.models import Appointment
from chat.models import Message
from django.contrib.auth.decorators import login_required
from .utils import render_to_pdf
from django.template.loader import get_template
from django.utils import timezone

from wsgiref.util import FileWrapper  # this used in django
from mimetypes import guess_type

from .models import Doctor
from patient.models import Patient


# Create your views here.
@login_required
def doctor_home(request):
    doctor = Doctor.objects.doctor(request)
    # for showing messages
    msgs = doctor.message_set.all()
    if msgs:
        request.session['messages'] = True
        request.session['total_messages'] = msgs.filter(from_patient=True, display=True).count()
        request.session['default_patient_pk'] = msgs.last().patient.pk
    return render(request, 'doctor/appointments.html', {'object': doctor})


@login_required
def download_report(request, ap_pk):
    appointment = Appointment.objects.get(pk=ap_pk)
    filepath = appointment.report.path
    download_obj = 'Report-' + appointment.patient.full_name
    with open(filepath, 'rb') as f:
        wrapper = FileWrapper(f)
        mimetype = 'application/force-download'
        gussed_mimetype = guess_type(filepath)[0]  # filename.mp4
        print('gussed_mimetype', gussed_mimetype)
        if gussed_mimetype:
            mimetype = gussed_mimetype
        response = HttpResponse(wrapper, content_type=mimetype)
        response['Content-Disposition'] = "attachment;filename=%s" % download_obj
        response['X-SendFile'] = str(download_obj)
        return response


@login_required
def appointments(request, slug, doctor_pk,  *args, **kwargs):
    doctor = Doctor.objects.doctor(request)
    appointment_list = doctor.appointment_set.all().new()
    approved_appointments = doctor.appointment_set.all().filter(approved=True)
    disapproved_appointments = doctor.appointment_set.all().filter(disapproved=True)
    pending_appointments = doctor.appointment_set.all().filter(pending=True)
    done_appointments = doctor.appointment_set.all().filter(done=True)
    form = UploadReportForm(request.POST or None, request.FILES or None)

    if request.method == 'POST':
        ap_pk = request.POST.get('ap_pk')
        appointment = Appointment.objects.get(pk=ap_pk)
        form = UploadReportForm(request.POST, request.FILES, instance=appointment)
        if form.is_valid():
            form.save()

    if approved_appointments:
        request.session['approved_appointments'] = True
    else:
        request.session['approved_appointments'] = False
    if disapproved_appointments:
        request.session['disapproved_appointments'] = True
    else:
        request.session['disapproved_appointments'] = False
    if pending_appointments:
        request.session['pending_appointments'] = True
    else:
        request.session['pending_appointments'] = False
    if done_appointments:
        request.session['done_appointments'] = True
    else:
        request.session['done_appointments'] = False

    if request.method == 'POST':
        ap_pk = request.POST.get('ap_pk')
        appointment = Appointment.objects.get(pk=ap_pk)
        form = UploadReportForm(request.POST, request.FILES, instance=appointment)
        if form.is_valid():
            form.save()

    approved = doctor.appointment_set.all().filter(approved=True)
    for appointment in approved:
        if timezone.now().date() > appointment.appointment_date:
            appointment.done = True
            appointment.approved = False
            appointment.save()
    done_appointments = doctor.appointment_set.all().filter(done=True)
    context = {
        'slug': slug,
        'object': doctor,
        'appointment_list': appointment_list,
        'approved_appointments': approved_appointments,
        'disapproved_appointments': disapproved_appointments,
        'pending_appointments': pending_appointments,
        'done_appointments': done_appointments,
        'form': form
    }
    # for showing messages
    msgs = doctor.message_set.all()
    print(msgs, msgs)
    if msgs:
        request.session['messages'] = True
        request.session['total_messages'] = msgs.filter(from_patient=True, display=True).count()
        request.session['default_patient_pk'] = msgs.last().patient.pk
    return render(request, 'doctor/appointments.html', context)


@login_required
def preview(request, pk):
    doctor_obj = Doctor.objects.get(pk=pk)
    if request.session.get('role') == 'patient':
        patient_pk = request.session.get('pk')
        patient_obj = Patient.objects.get(pk=patient_pk)
        appointment_status = None
        appointment = Appointment.objects.filter(patient=patient_obj, doctor=doctor_obj)
        if appointment:
            appointment_status = appointment.first().status()
        return render(request, 'doctor/preview.html', {'object': doctor_obj, 'appointment_status': appointment_status})

    if request.session.get('role') == 'doctor':
        # for showing messages
        msgs = doctor_obj.message_set.all()
        if msgs:
            request.session['messages'] = True
            request.session['total_messages'] = msgs.filter(from_patient=True, display=True).count()
            request.session['default_patient_pk'] = msgs.last().patient.pk
    return render(request, 'doctor/preview.html', {'object': doctor_obj})


@login_required
def patient_list(request):
    doctor = Doctor.objects.doctor(request)
    done_appointments = doctor.appointment_set.filter(done=True)
    context = {
        'object': doctor,
        'done_appointments': done_appointments
    }
    # for showing messages
    msgs = doctor.message_set.all()
    if msgs:
        request.session['messages'] = True
        request.session['total_messages'] = msgs.filter(from_patient=True, display=True).count()
        request.session['default_patient_pk'] = msgs.last().patient.pk
    return render(request, 'doctor/patient_list.html', context)


@login_required
def update_profile(request):
    doctor = Doctor.objects.doctor(request)
    form = UpdateProfileForm(request.POST or None, request.FILES or None, instance=doctor)
    if form.is_valid():
        form.save()
        return redirect('doctor:doctor_preview', pk=doctor.pk)
    context = {'form': form, 'object': doctor}
    # for showing messages
    doctor = Doctor.objects.get(pk=request.session.get('pk'))
    msgs = doctor.message_set.all()
    if msgs:
        request.session['messages'] = True
        request.session['total_messages'] = msgs.filter(from_patient=True, display=True).count()
        request.session['default_patient_pk'] = msgs.last().patient.pk
    return render(request, 'doctor/update_profile.html', context)


def view_profile(request):
    doctor_pk = request.GET.get("doctor_pk")
    doctor = Doctor.objects.get(pk=doctor_pk)
    appointment_status = None
    if request.session.get('role') == 'patient':
        doctor_pk = request.GET.get("doctor_pk")
        doctor = Doctor.objects.get(pk=doctor_pk)
        patient = Patient.objects.patient(request)
        appointment = Appointment.objects.filter(patient=patient, doctor=doctor)
        if appointment:
            appointment_status = appointment.first().status()

    # for showing messages
    if request.session.get('role') == 'doctor':
        doctor = Doctor.objects.doctor(request)
        msgs = doctor.message_set.all()
        if msgs:
            request.session['messages'] = True
            request.session['total_messages'] = msgs.filter(from_patient=True, display=True).count()
            request.session['default_patient_pk'] = msgs.last().patient.pk
    context = {
        'object': doctor,
        'appointment_status': appointment_status
    }
    return render(request, 'doctor/preview.html', context)


def create_appointment(request):
    msg_patient = request.POST.get('msg_patient')
    patient_pk = request.POST.get('patient_pk')
    doctor_pk = request.POST.get('doctor_pk')
    doctor = Doctor.objects.get(pk=doctor_pk)
    patient = Patient.objects.get(pk=patient_pk)

    Appointment.objects.create(patient=patient, doctor=doctor, msg_patient=msg_patient)
    return redirect('patient:patient_appointments', status='New')


@login_required
def respond(request, ap_pk):
    appointment = Appointment.objects.get(pk=ap_pk)
    # for approve
    form = AppointmentRespondForm(request.POST or None, instance=appointment)
    if form.is_valid():
        if appointment.pending and appointment.approved:
            appointment.pending = False
            appointment.save()
        msg_doctor = "Your Appointment has been Approved"
        Message.objects.create(patient=appointment.patient, doctor=appointment.doctor, msg_doctor=msg_doctor, from_doctor=True)
        form.save()
        return redirect("doctor:appointments", slug='fixed', doctor_pk=appointment.doctor.pk)
    status = request.GET.get('status')
    context = {
        'form': form,
        'appointment': appointment,
        'status': status
    }
    # for showing messages
    doctor = Doctor.objects.doctor(request)
    msgs = doctor.message_set.all()
    if msgs:
        request.session['messages'] = True
        request.session['total_messages'] = msgs.filter(from_patient=True, display=True).count()
        request.session['default_patient_pk'] = msgs.last().patient.pk
    return render(request, 'doctor/respond.html', context)


def create_msg(request):
    ap_pk = request.POST.get('ap_pk')
    appointment = Appointment.objects.get(pk=ap_pk)
    doctor = appointment.doctor
    patient = appointment.patient
    msg_disapprove = request.POST.get('msg_disapprove')

doctor/templates/doctor/appointment_table.html
{% if slug and not appointments %}
{% load static %}
<h3 class="text-danger m-4">No {{ slug }} Appointments!</h3>
{% else %}
<table class="table-bordered my-3" cellpadding="10">
            <thead>
              <tr class="text-center">
                <td></td>
                <td>Name</td>
                 <td>Date</td>
                <td>Time</td>
                <td>Location</td>
                <td>{% if slug == 'done' %}Status{% else %}Token No.{% endif %}</td>
                {% if slug == 'done' %}
                 <td colspan="">Generate/Upload/View Report</td>
                 {% endif %}
                {% if slug == 'pending' %}
                <td></td>
                <td></td>
                {% endif %}
              </tr>
            </thead>
            <tbody>
            {% for appointment in appointments %}
            <tr class="text-success text-center">
              <td><img src="{{ appointment.patient.image.url }}" width="70px"></td>
                <td><u><a href="{% url 'patient:patient_account' pk=appointment.patient.pk %}">{{ appointment.patient.full_name }}</a></u></td>
              <td>{{ appointment.appointment_date }}</td>
              <td>{{ appointment.appointment_time }}</td>
              <td>{{ appointment.location }}</td>
              <td class="text-danger">{% if slug == 'done' %}Completed{% else %}{{ appointment.token_no }}{% endif %}</td>
              {% if slug == 'approved' or slug == 'disapproved' %}
              <td><a href="{% url 'chat:message_view' patient_pk=appointment.patient.pk %}">View Message Sent</a></td>
              {% endif %}
              {% if slug == 'pending' %}
              <td><form action="{% url 'doctor:respond' ap_pk=appointment.pk %}">
                <input type="hidden" name="status" value="approve">
                <input type="submit" value="Approve" class="btn btn-outline-danger btn-sm">
              </form></td>
             <td><form action="{% url 'doctor:respond' ap_pk=appointment.pk %}">
                 <input type="hidden" name="status" value="disapprove">
                 <input type="submit" value="Disapprove" class="btn btn-outline-danger btn-sm">
             </form></td>
             {% endif %}
             {% if slug == 'done' %}
                <td colspan="">
                    {% if appointment.report_generated %}
                    {% if not appointment.report %}
                    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
                     {{ form.as_p }}
                        <input type="hidden" name="ap_pk" value="{{ appointment.pk }}">
                        <input type="submit" class="btn btn-sm btn-success" value="upload">
                    </form>
                    {% else %}
                    <a class="btn btn-sm btn-outline-success" href="{{ appointment.report.url }}" target="_blank">view</a>
                    <a class="btn btn-sm btn-success mt-1" href="{% url 'doctor:download_report' ap_pk=appointment.pk %}">Download</a>
                    {% endif %}
                    {% else %}
                    <a href="{% url 'doctor:generate_report' ap_pk=appointment.pk %}" class="btn btn-sm btn-success">Generate Report</a>
                    {% endif %}
                </td>
             {% endif %}
            </tr>
            {% endfor %}
            </tbody>
</table>


{% endif %}

doctor/templates/doctor/appointments.html
{% extends 'doctor/base_doctor.html' %}

{% block title %}
{% if slug == 'requests' %}
Appointment Requests
{% else %}
{{ slug|capfirst }} Appointments
{% endif %}
{% endblock %}

{% block main %}

{% if slug == 'requests' %}
 <div class="row mx-1">
     {% if appointment_list %}
     {% for appointment in appointment_list %}
        <div class="box-shadow mx-2 border border-info col-5 no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-3 d-flex flex-column position-statFic">
          <table class="table-bordered" cellpadding="5">
            <thead>
              <tr class="text-center">
                <td>Token No.</td>
                <td>Name</td>
                <td>Date</td>
              </tr>
            </thead>
            <tbody>
            <tr class="text-primary text-center">
              <td>{{ appointment.token_no }}</td>
              <td>{{ appointment.patient.full_name }}</td>
              <td>{{ appointment.created.date }}</td>
            </tr>
            <tr>
              <td colspan="4" class="text-center">Description</td>
            </tr>
            <tr>
              <td class="text-primary text-justify" colspan="4">{{ appointment.msg_patient|truncatewords:26 }}</td>
            </tr>

            </tbody>
          </table>
          <div class="row mt-2">
              <div class="col">
            <a href="{% url 'patient:patient_account' pk=appointment.patient.pk %}" class="btn btn-outline-info btn-sm float-right">View Profile</a>
              </div>
              <div class="col">
            <form action="{% url 'doctor:respond' ap_pk=appointment.pk %}">
                <input type="hidden" name="status" value="respond">
                <input type="submit" value="Respond" class="btn btn-success btn-sm float-left">
            </form>
              </div>
          </div>
        </div>
      </div>
     {% endfor %}
     {% else %}
     <h4 class="mt-3 font-italic ml-3 text-danger">No Appointments Yet!!</h4>
     {% endif %}
</div>
{% elif slug == 'fixed' %}
{% include 'doctor/appointment_table.html' with appointments=approved_appointments %}
{% elif slug == 'pending' %}
{% include 'doctor/appointment_table.html' with appointments=pending_appointments %}
{% elif slug == 'done' %}
{% include 'doctor/appointment_table.html' with appointments=done_appointments %}
{% elif slug == 'disapproved' %}
{% if disapproved_appointments %}
<table class="table-bordered my-3 col-10" cellpadding="10">
            <thead>
              <tr class="text-center">
                <td colspan="2">Name</td>
                <td>Token No</td>
                <td>Message</td>
                <td>Profile</td>
                <td></td>
              </tr>
              {% for appointment in disapproved_appointments %}
              <tr class="text-muted">
                <td><img src="{{ appointment.patient.image.url }}" width="80px"></td>
                <td>{{ appointment.patient.full_name }}</td>
                <td>{{ appointment.token_no }}</td>
                <td><a href="{% url 'chat:message_view' patient_pk=appointment.patient.pk %}" class="btn btn-sm btn-outline-success">View Message Sent</a></td>
                <td><a href="{% url 'patient:patient_account' pk=appointment.patient.pk %}" class="btn btn-sm btn-outline-success">View Profile</a></td>
                <td><a href="{% url 'doctor:delete_appointment' ap_pk=appointment.pk %}" class="btn btn-sm btn-dark">Delete</a></td>
              </tr>
            {% endfor %}
              </thead>
</table>

{% else %}
<h4 class="mt-3 font-italic ml-3 text-danger">No Disapproved Appointments!</h4>
{% endif %}


{% endif %}
{% endblock %}

doctor/templates/doctor/respond.html
{% extends 'doctor/base_doctor.html' %}
{% load static %}
{% block title %}Respond to Appointment Request{% endblock %}
<!--{% url 'doctor:view_profile' %}-->
{% block main %}
<div class="container">
    {% if status == 'respond' %}
    <a href="#" class="btn btn-outline-success btn_approve">Approve</a>
    <a href="#" class="btn btn-outline-success mx-2 btn_disapprove">Disapprove</a>
    <a href="#" class="btn btn-outline-success btn_more_info">Request More Info</a>

    <div class="col-6 mt-5 border patient_msg">
    <h4 class="mt-3 text-danger">Patient Message</h4>
    <hr>
    <p class="p-3 text-muted text-justify">
        {{ appointment.msg_patient }}
    </p>
    <div class="">
    <a href="{% url 'patient:patient_account' pk=appointment.patient.pk %}" class="btn btn-outline-success">View Patient's Profile</a>
    </div>
</div>
    {% endif %}



    <!---  Approve View  --->
    <div style="{% if not status == 'approve' %}display: none;{% endif %}" class="approve mt-5 row">
    <div class="col-8">
    <div class="pr-5 col-9">
        <h4 class="text-info">Approve Appointment</h4>
     <form method="POST" action="{% url 'doctor:respond' ap_pk=appointment.pk %}"> {% csrf_token %}
         {{ form.as_p }}
         <input type="submit" class="btn btn-primary" value="Submit">
     </form>
        </div>
    </div>
    {% if status == 'respond' %}
    <div class="col-4 border">
        <h4 class="text-center my-3 text-danger">Patient Message</h4>
        <hr>
        <p class="p-4 text-muted text-justify">
            {{ appointment.msg_patient }}
        </p>
        <div class="text-center">
        <a href="{% url 'patient:patient_account' pk=appointment.patient.pk %}" class="btn btn-outline-success">View Patient's Profile</a>
        </div>
    </div>
    {% endif %}
    </div>


    <!---  Disapprove View  --->
    <div style="{% if not status == 'disapprove' %}display: none;{% endif %}" class="disapprove mt-5 row">
    <div class="col-8">
    <div class="pr-5 col-10">
        <h4 class="text-info mb-3">Disapprove Appointment</h4>
     <form method="POST" action="{% url 'doctor:create_msg' %}"> {% csrf_token %}
        <input type="hidden" name="ap_pk" value="{{ appointment.pk }}">
        <textarea name="msg_disapprove" class="form-control" rows="7" placeholder="Enter Reason for disapproving the request..."></textarea>
        <input type="submit" class="btn btn-primary mt-3" value="Submit">
     </form>
        </div>
    </div>
    {% if status == 'respond' %}
    <div class="col-4 border">
        <h4 class="text-center my-3 text-danger">Patient Message</h4>
        <hr>
        <p class="p-4 text-muted text-justify">
            {{ appointment.msg_patient }}
        </p>
        <div class="text-center">
        <a href="{% url 'patient:patient_account' pk=appointment.patient.pk %}" class="btn btn-outline-success">View Patient's Profile</a>
        </div>
    </div>
    {% endif %}
    </div>

     <!---  Request More Info View  --->
    <div style="display: none;" class="more_info mt-5 row">
    <div class="col-8">
    <div class="pr-5 col-10">
        <h4 class="text-info mb-3">Request More Info</h4>
     <form method="POST" action="{% url 'doctor:create_msg' %}"> {% csrf_token %}
       <input type="hidden" name="ap_pk" value="{{ appointment.pk }}">
       <textarea name="msg_info" class="form-control" rows="7" placeholder="Enter Additional Information You Need From Patient..."></textarea>
       <input type="submit" class="btn btn-primary mt-3" value="Submit">
     </form>
        </div>
    </div>
    <div class="col-4 border">
        <h4 class="text-center my-3 text-danger">Patient Message</h4>
        <hr>
        <p class="p-4 text-muted text-justify">
            {{ appointment.msg_patient }}
        </p>
        <div class="text-center">
        <a href="{% url 'patient:patient_account' pk=appointment.patient.pk %}" class="btn btn-outline-success">View Patient's Profile</a>
        </div>
    </div>
    </div>

</div>
{% endblock %}


<!--<div class="row">-->
<!--<div class="col-8">-->
<!--    <div class="pr-5 col-9">-->
<!--     <form method="POST" action="{% url 'doctor:respond' ap_pk=appointment.pk %}"> {% csrf_token %}-->
<!--         {{ form.as_p }}-->
<!--         <input type="submit" class="btn btn-primary mt-3" value="Submit">-->
<!--     </form>-->
<!--    </div>-->
<!--</div>-->
<!--<div class="col-4 border">-->
<!--    <h4 class="text-center my-3 text-danger">Patient Message</h4>-->
<!--    <hr>-->
<!--    <p class="p-4 text-muted text-justify">-->
<!--        {{ appointment.msg_patient }}-->
<!--    </p>-->
<!--    <div class="text-center">-->
<!--    <a href="{% url 'patient:patient_account' pk=appointment.patient.pk %}" class="btn btn-outline-success">View Patient's Profile</a>-->
<!--    </div>-->
<!--</div>-->
<!--</div>-->