HMS/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LogoutView
from django.conf.urls import url, include
from django.contrib import admin
from .views import (
    home_page,
    register_page,
    login_page,
)
from search.views import search

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page, name='home'),
    url(r'^register/$', register_page, name='register'),
    url(r'^login/$', login_page, name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^doctor/', include('doctor.urls', namespace='doctor')),
    url(r'^patient/', include('patient.urls', namespace='patient')),
    url(r'^messages/', include('chat.urls', namespace='chat')),
    url(r'^search/$', search, name='search'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # necessary if you  want to serves media files locally
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.conf.urls import url
from .views import (
    create_message,
    delete_msg,
    message_view,
)

app_name = "chat"

urlpatterns = [
    url(r'^new/$', create_message, name='create_message'),
    url(r'^delete/(?P<msg_pk>\d+)/$', delete_msg, name='delete_msg'),
    url(r'^messages/(?P<patient_pk>\d+)/$', message_view, name='message_view'),
]

# (?P<pk>\d+)
# (?P<slug>[\w-]+)

doctor/urls.py
from django.conf.urls import url
from .views import (
    doctor_home,
    appointments,
    preview,
    patient_list,
    update_profile,
    respond,
    view_profile,
    create_msg,
    create_appointment,
    download_report,
    GeneratePDF,
    delete_appointment,
    generate_report,
)

app_name = "doctor"

urlpatterns = [
    url(r'^appointments/(?P<doctor_pk>\d+)/(?P<slug>[\w-]+)/$', appointments, name='appointments'),
    url(r'^info/(?P<pk>\d+)/$', preview, name='doctor_preview'),
    url(r'^patients/$', patient_list, name='patient_list'),
    url(r'^update/$', update_profile, name='update'),
    url(r'^respond/(?P<ap_pk>\d+)/$', respond, name='respond'),
    url(r'^send/$', create_msg, name='create_msg'),
    url(r'^profile/$', view_profile, name='view_profile'),
    url(r'^create-appointment/$', create_appointment, name='create_appointment'),
    url(r'^download-report/(?P<ap_pk>\d+)/$', download_report, name='download_report'),
    url(r'^pdf/(?P<ap_pk>\d+)/$', GeneratePDF.as_view(), name='GeneratePDF'),
    url(r'^delete/(?P<ap_pk>\d+)/$', delete_appointment, name='delete_appointment'),
    url(r'^report/(?P<ap_pk>\d+)/$', generate_report, name='generate_report'),
]

# (?P<pk>\d+)
# (?P<slug>[\w-]+)

patient/urls.py
from django.conf.urls import url
from .views import patient_account, update_profile, patient_appointments, message_view, doctor_list

app_name = "patient"

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', patient_account, name='patient_account'),
    url(r'^update/$', update_profile, name='update'),
    url(r'^appointments/(?P<status>[\w-]+)/$', patient_appointments, name='patient_appointments'),
    url(r'^messages/(?P<doctor_pk>\d+)/$', message_view, name='messages'),
    url(r'^doctor-list/$', doctor_list, name='doctor_list'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/navbar-top-fixed.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
  <!-- Custom Style -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
      <script src="{% static 'js/jquery.min.js' %}"></script>
          <script src="{% static 'js/custom.js' %}"></script>

      <script src="{% static 'js/dashboard.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

<!--    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">-->
<!--    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>-->
<!--    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>-->
</head>
<body>
	{% include 'navbar.html' %}
    <div class="container">
          {% if messages %}
          {% endif %}
      </div>
	{% block content %}
	{% endblock %}
</body>
</html>

templates/form.html
{% extends 'base.html' %}

{% block content %}
    

{% include 'style-contact.css' %}

<section class="contact-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="contact-text">
                        <h2>Contact Info</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                            labore et dolore magna aliqua.</p>
                        <table>
                            <tbody>
                                <tr>
                                    <td class="c-o">Address:</td>
                                    <td>856 Cordia Extension Apt. 356, Lake, US</td>
                                </tr>
                                <tr>
                                    <td class="c-o">Phone:</td>
                                    <td>(12) 345 67890</td>
                                </tr>
                                <tr>
                                    <td class="c-o">Email:</td>
                                    <td>info.colorlib@gmail.com</td>
                                </tr>
                                <tr>
                                    <td class="c-o">Fax:</td>
                                    <td>+(12) 345 67890</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-lg-7 offset-lg-1">
                    <form method="POST" class="contact-form">{% csrf_token %}
                        <div class="row">
                            <div class="col-lg-6">
                                <input type="text" name="full_name" placeholder="Your Name">
                            </div>
                            <div class="col-lg-6">
                                <input type="text" name="email" placeholder="Your Email">
                            </div>
                            <div class="col-lg-12">
                                <textarea placeholder="Your Message" name="content"></textarea>
                                <button type="submit">Submit Now</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

 

templates/index.html
{% extends 'base.html' %}

{% block content %}
	<div class="container">
		<h1 class="text-center">Welcome to Hospital Management System</h1>

		{% if not user.is_authenticated %}
			<h3 class="text-center text-muted">Register as a Doctor or Patient </h3>
		<div class="card py-3 col-5 mx-auto mt-5">
		<div class="mx-auto col-6">
			<a href="{% url 'register' %}" class="btn btn-success">Register Here</a>
			<h5 class="my-3 ml-5">or</h5>
		</div>
			<div class="row">
				<div class="col-6">
				<p class="float-right text-secondary mt-2">Already Registered?</p>
				</div>
				<div class="col-6">
					<a href="{% url 'login' %}" class="btn btn-outline-success float-left">Login</a>
				</div>
			</div>
		</div>
		</div>
		{% else %}
		<p class="col-6 mt-5 text-justify mx-auto">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		<div class="col-6 mx-auto mt-5">
			<hr>
			<h3 class="ml-5 mb-4">Search Doctor</h3>
			<div class="text-center">
 				<!-- pk={{ request.session.pk }}-->
				<form class="form-inline mt-5 ml-5 mt-md-0" action="{% url 'search' %}">
					<input type="hidden" name="patient_pk" value="{{ request.session.pk }}">
     				  <input style="width:280px;" class="form-control mr-sm-2" autofocus type="text" placeholder="Enter Medical Category" aria-label="Search" name="q">
					  <button class="btn btn-success text-center my-sm-0" type="submit">Search</button>
					  <p class="text-muted mt-2">(e.g cardialogy, Heart, Vision)</p>
    			</form>
			</div>
		</div>
		{% endif %}
	</div>

{% endblock %}

templates/navbar.html
{% url 'home' as home_url %}
{% url 'patient:doctor_list' as doctor_list %}
{% url 'doctor:appointments' as doctor_app_url %}
{% url 'chat:message_view' as chat_url %}
{% url 'patient:patient_account' as patient_url %}
{% url 'patient:patient_appointments' as patient_app_url %}
{% url 'patient:messages' as patient_msg_url %}
{% url 'logout' as logout %}
{% url 'login' as login %}
{% url 'register' as register %}


<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
<!--  <a class="navbar-brand" href="#">BlogApp</a>-->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse ml-5" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <!--  get session variable request.session['role']  -->
      {% if request.session.role == 'doctor' %}
      <li class="nav-item {% if request.path == doctor_app_url %}active{% endif %}">
        <a class="nav-link" href="{% url 'doctor:appointments' slug='requests' doctor_pk=request.session.pk %}">Dashboard</a>
      </li>
      {% if request.session.messages %}
      <li class="nav-item {% if request.path == chat_url %}active{% endif %}">
        <a class="nav-link" href="{% url 'chat:message_view' patient_pk=request.session.default_patient_pk %}">
          Messages<sup class=" text-warning">
         {% if request.session.total_messages <= 0 %} {% else %} {{  request.session.total_messages }} {% endif %}
        </sup></a>
      </li>
      {% endif %}
      {% elif request.session.role == 'patient' %}
      <li class="nav-item {% if request.path == doctor_list  %}active{% endif %}">
        <a class="nav-link" href="{% url 'patient:doctor_list' %}">Doctors <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == patient_url %}active{% endif %}">
        <a class="nav-link" href="{% url 'patient:patient_account' pk=request.session.pk %}">Profile</a>
      </li>
      <li class="nav-item {% if request.path == patient_app_url %}active{% endif %}">
        <a class="nav-link" href="{% url 'patient:patient_appointments' status='appointments' %}">Appointments</a>
      </li>
      {% if request.session.messages %}
      <li class="nav-item {% if request.path == patient_msg_url %}active{% endif %}">
        <a class="nav-link" href="{% url 'patient:messages' doctor_pk=request.session.default_doctor_pk %}">
          Messages<sup class="text-warning">
         {% if request.session.total_messages <= 0 %} {% else %} {{  request.session.total_messages }} {% endif %}
        </sup></a>
      </li>
      {% endif %}
      {% endif %}
      {% if not user.is_authenticated %}
      <li class="nav-item {% if request.path == register %}active{% endif %}">
        <a class="nav-link" href="{% url 'register' %}">Register</a>
      </li>
       <li class="nav-item {% if request.path == login %}active{% endif %}">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      {% else %}
       <li class="nav-item {% if request.path == logout %}active{% endif %}">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>	

<!-- href="" & action="" contains the corrosponding paths in urlpatterns -->

templates/search_q.html
{% extends 'base.html' %}

{% block content %}
	<div class="container">
        {% if object_list %}
        <h3 class="text-muted">Doctors for <span class="text-warning">{{ q }}</span></h3>
        <div class="row mt-5">

        {% for object in object_list %}
            <div class="card mx-5 mb-5" style="width: 16rem;">
              <img src="{{ object.image.url }}" class="card-img-top" alt="...">
              <div class="card-body">
                  <h5 class="card-title">{{ object.full_name }}</h5>
                  <p class="mb-3 text-success h6">{{ object.category }}</p>
                <p class="card-text text-justify">{{ object.about|truncatewords:12 }}</p>
                <form method="GET" action="{% url 'doctor:view_profile' %}">
                    <input type="hidden" name="patient_pk" value="{{ request.session.pk }}">
                    <input type="hidden" name="doctor_pk" value="{{ object.pk }}">
                    <input type="submit" value="View Profile" class="btn btn-lg btn-block btn-success">
               </form>
              </div>
            </div>

            {% endfor %}
            </div>
        {% else %}
        <h3 class="text-muted mt-5">No Doctors for <span class="text-warning">{{ q }}</span></h3>
        {% endif %}
    </div>
{% endblock %}


<div class="card col-4 mb-4 mx-5 shadow-sm">
              <div class="card-header">
                  <img src="{{ object.image.url }}" width="50%">
              </div>
              <div class="card-body">
                <h4 class="card-title pricing-card-title">{{ object.full_name }}</h4>
                <h5 class="text-danger">{{ object.category }}</h5>
                  <h5 class="text-muted text-justify">{{ object.about|truncatewords:15 }}</h5>

               <form method="GET" action="{% url 'doctor:view_profile' %}">
                    <input type="hidden" name="patient_pk" value="{{ request.session.pk }}">
                    <input type="hidden" name="doctor_pk" value="{{ object.pk }}">
                    <input type="submit" value="View Profile" class="btn btn-lg btn-block btn-primary">
               </form>

<!--                <a href="{{ object.get_absolute_url }}" type="button" class="btn btn-lg btn-block btn-primary">View Profile</a>-->
              </div>
            </div>