HMS/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LogoutView
from django.conf.urls import url, include
from django.contrib import admin
from .views import (
    home_page,
    register_page,
    login_page,
)
from search.views import search

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page, name='home'),
    url(r'^register/$', register_page, name='register'),
    url(r'^login/$', login_page, name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^doctor/', include('doctor.urls', namespace='doctor')),
    url(r'^patient/', include('patient.urls', namespace='patient')),
    url(r'^messages/', include('chat.urls', namespace='chat')),
    url(r'^search/$', search, name='search'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # necessary if you  want to serves media files locally
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.conf.urls import url
from .views import (
    create_message,
    delete_msg,
    message_view,
)

app_name = "chat"

urlpatterns = [
    url(r'^new/$', create_message, name='create_message'),
    url(r'^delete/(?P<msg_pk>\d+)/$', delete_msg, name='delete_msg'),
    url(r'^messages/(?P<patient_pk>\d+)/$', message_view, name='message_view'),
]

# (?P<pk>\d+)
# (?P<slug>[\w-]+)

doctor/urls.py
from django.conf.urls import url
from .views import (
    doctor_home,
    appointments,
    preview,
    patient_list,
    update_profile,
    respond,
    view_profile,
    create_msg,
    create_appointment,
    download_report,
    GeneratePDF,
    delete_appointment,
    generate_report,
)

app_name = "doctor"

urlpatterns = [
    url(r'^appointments/(?P<doctor_pk>\d+)/(?P<slug>[\w-]+)/$', appointments, name='appointments'),
    url(r'^info/(?P<pk>\d+)/$', preview, name='doctor_preview'),
    url(r'^patients/$', patient_list, name='patient_list'),
    url(r'^update/$', update_profile, name='update'),
    url(r'^respond/(?P<ap_pk>\d+)/$', respond, name='respond'),
    url(r'^send/$', create_msg, name='create_msg'),
    url(r'^profile/$', view_profile, name='view_profile'),
    url(r'^create-appointment/$', create_appointment, name='create_appointment'),
    url(r'^download-report/(?P<ap_pk>\d+)/$', download_report, name='download_report'),
    url(r'^pdf/(?P<ap_pk>\d+)/$', GeneratePDF.as_view(), name='GeneratePDF'),
    url(r'^delete/(?P<ap_pk>\d+)/$', delete_appointment, name='delete_appointment'),
    url(r'^report/(?P<ap_pk>\d+)/$', generate_report, name='generate_report'),
]

# (?P<pk>\d+)
# (?P<slug>[\w-]+)

patient/urls.py
from django.conf.urls import url
from .views import patient_account, update_profile, patient_appointments, message_view, doctor_list

app_name = "patient"

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', patient_account, name='patient_account'),
    url(r'^update/$', update_profile, name='update'),
    url(r'^appointments/(?P<status>[\w-]+)/$', patient_appointments, name='patient_appointments'),
    url(r'^messages/(?P<doctor_pk>\d+)/$', message_view, name='messages'),
    url(r'^doctor-list/$', doctor_list, name='doctor_list'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager
)


# Create your models here.
class UserManager(BaseUserManager):
    def create_user(self, email, password=None, is_active=True, is_staff=False, is_admin=False):
        if not email:
            raise ValueError("User must have an email")
        if not password:
            return ValueError("User must have a password")
        user_obj = self.model(
            email=self.normalize_email(email)
        )
        user_obj.set_password(password)
        user_obj.staff = is_staff
        user_obj.is_active = is_active
        user_obj.admin = is_admin
        user_obj.save(using=self._db)
        return user_obj

    def create_staffuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
            is_staff=True
        )
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
            is_staff=True,
            is_admin=True
        )
        return user


class User(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    full_name = models.CharField(max_length=150, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        if self.is_admin:
            return True
        return self.staff

    @property
    def is_admin(self):
        return self.admin

appointments/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.conf import settings
from django.db.models import Q
from django.utils import timezone

from patient.models import Patient
from doctor.models import Doctor
from HMS.utils import unique_token_no_generator

User = settings.AUTH_USER_MODEL


class AppointmentManagerQuerySet(models.query.QuerySet):
	def new(self):
		return self.filter(approved=False, disapproved=False, pending=False, done=False)

	def not_new(self):
		lookups = (Q(approved=True) |
				   Q(disapproved=True) |
				   Q(pending=True) |
				   Q(done=True))
		return self.filter(lookups)


class AppointmentManager(models.Manager):
	def get_queryset(self):
		return AppointmentManagerQuerySet(self.model, using=self._db)

	def new(self):
		return self.get_queryset().new()

	def not_new(self):
		return self.get_queryset().not_new()


class Appointment(models.Model):
	patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True, blank=True)
	doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, null=True, blank=True)

	msg_patient = models.TextField(null=True, blank=True)
	msg_doctor = models.TextField(null=True, blank=True)

	approved = models.BooleanField(default=False)
	disapproved = models.BooleanField(default=False)
	pending = models.BooleanField(default=False)
	done = models.BooleanField(default=False)
	location = models.CharField(max_length=200, null=True, blank=True)

	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	appointment_date = models.DateField(null=True, blank=True)
	appointment_time = models.TimeField(null=True, blank=True)

	diseases = models.CharField(max_length=300, null=True, blank=True)
	token_no = models.CharField(max_length=55, null=True, blank=True)
	report_generated = models.BooleanField(default=False)
	report = models.FileField(upload_to='reports', null=True, blank=True, verbose_name=' ')

	objects = AppointmentManager()

	def __str__(self):
		return str(self.doctor.full_name) + ' | ' + str(self.patient.full_name)

	def status(self):
		if self.approved:
			return "Approved"
		if self.disapproved:
			return "Disapproved"
		if self.pending:
			return "Pending"
		if self.done:
			return "Done"
		else:
			return "New"

	class Meta:
		ordering = ['-updated', '-created']


def pre_save_token_no(sender, instance, *args, **kwargs):
	if not instance.token_no:
		instance.token_no = unique_token_no_generator(instance)


pre_save.connect(pre_save_token_no, sender=Appointment)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from doctor.models import Doctor
from django.contrib.auth import authenticate, login, get_user_model
User = get_user_model()


class UserAdminCreationForm(forms.ModelForm):
    """
    A form for creating new users. Includes all the required
    fields, plus a repeated password.
    """
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('full_name', 'email',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_active = False  # send confirmation email via signals
        # obj = EmailActivation.objects.create(user=user)
        # obj.send_activation_email()
        if commit:
            user.save()
        return user


class UserDetailChangeForm(forms.ModelForm):
    full_name = forms.CharField(label='Name', required=False, widget=forms.TextInput(attrs={"class": 'form-control'}))

    class Meta:
        model = User
        fields = ['full_name']


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('full_name', 'email', 'password', 'is_active', 'admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class UpdateProfileForm(forms.ModelForm):

    class Meta:
        model = Doctor
        # fields = '__all__'
        # exclude = ['doctor_user']
        fields = ('address', 'about', 'awards', 'image', 'category')

        help_texts = {
            'awards': 'Hold down "Control", or "Command" on a Mac, to select more than one.',
        }

appointments/forms.py
from django import forms
from .models import Appointment
from django.contrib.auth import authenticate, login, get_user_model
User = get_user_model()


class AppointmentRespondForm(forms.ModelForm):
    location = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Location'}
    ), label='')

    approved = forms.BooleanField(widget=forms.CheckboxInput(attrs={'checked': 'True', 'class': 'hide_this', 'style': 'display:none'}), label='')
    pending = forms.BooleanField(widget=forms.CheckboxInput(attrs={'checked': 'False', 'class': 'hide_this', 'style': 'display:none'}), label='')

    class Meta:
        model = Appointment
        # fields = ('appointment_date', 'appointment_time', 'location')
        fields = ('appointment_date', 'appointment_time', 'location', 'approved', 'pending')

        widgets = {
            'appointment_date': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'yyy-mm-dd', 'type': 'date'}),
            'appointment_time': forms.TimeInput(attrs={'class': 'form-control', 'placeholder': 'hr:min', 'type': 'time'}),
            # 'location': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Location'}),
            # 'msg_doctor': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter Message'},),
        }


class UploadReportForm(forms.ModelForm):
    # report = forms.FileField(widget=forms.FileField())

    class Meta:
        model = Appointment
        fields = ('report', )

patient/forms.py
from django import forms
from .models import Patient
from django.contrib.auth import authenticate, login, get_user_model
User = get_user_model()


class PatientProfileForm(forms.ModelForm):

    class Meta:
        model = Patient
        fields = '__all__'
        exclude = ['patient_user', 'full_name', 'role']
        # fields = ('about', 'awards', 'image')

        help_texts = {
            'weight': '(in kgs)',
        }

accounts/views.py
from django.shortcuts import render

# Create your views here.

appointments/views.py
from django.shortcuts import render

patient/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import PatientProfileForm
from .models import Patient
from appointments.models import Appointment
from chat.models import Message
from doctor.models import Doctor
from django.db.models import Q
from django.utils import timezone
from django.contrib.auth.decorators import login_required


@login_required
def patient_home(request):
    patient = Patient.objects.patient(request)
    # for showing messages
    messages = patient.message_set.all().filter(from_doctor=True, display=True)
    if messages:
        request.session['messages'] = True
        request.session['total_messages'] = messages.count()
        request.session['default_doctor_pk'] = messages.last().doctor.pk
    return render(request, 'patient/home.html', {})


@login_required
def patient_account(request, pk):
    patient = Patient.objects.get(pk=pk)
    context = {'object': patient}

    # for showing messages
    if request.session.get('role') == 'patient':
        messages = patient.message_set.all()
        if messages:
            request.session['messages'] = True
            request.session['total_messages'] = messages.filter(from_doctor=True, display=True).count()
            request.session['default_doctor_pk'] = messages.last().doctor.pk
    return render(request, 'patient/account.html', context)


@login_required
def update_profile(request):
    patient = Patient.objects.patient(request)
    form = PatientProfileForm(request.POST or None, request.FILES or None, instance=patient)
    if form.is_valid():
        form.save()
        return redirect('patient:patient_account', pk=patient.pk)
    context = {'form': form, 'object': patient}
    return render(request, 'patient/update_profile.html', context)


@login_required
def patient_appointments(request, status):
    patient = Patient.objects.patient(request)
    new_appointments = patient.appointment_set.all().new()
    appointments = patient.appointment_set.all().not_new().filter(done=False)
    past_appointments = patient.appointment_set.all().filter(done=True)

    approved = patient.appointment_set.all().filter(approved=True)
    for appointment in approved:
        if timezone.now().date() > appointment.appointment_date:
            appointment.done = True
            appointment.approved = False
            appointment.save()
    context = {
        'new_appointments': new_appointments,
        'appointments': appointments,
        'past_appointments': past_appointments,
        'status': status
    }
    # for showing messages
    messages = patient.message_set.all().filter(from_doctor=True, display=True)
    if messages:
        request.session['messages'] = True
        request.session['total_messages'] = messages.count()
        request.session['default_doctor_pk'] = messages.last().doctor.pk
    return render(request, 'patient/appointments.html', context)


@login_required
def message_view(request, doctor_pk):
    patient = Patient.objects.patient(request)
    appointments = patient.appointment_set.all().not_new()
    doctor = Doctor.objects.get(pk=doctor_pk)

    # for showing messages
    messages = patient.message_set.all().filter(from_doctor=True, display=True)
    if messages:
        request.session['messages'] = True
        request.session['total_messages'] = messages.count()
        request.session['default_doctor_pk'] = messages.last().doctor.pk

    doctor_msgs = Message.objects.filter(patient=patient, doctor=doctor, from_doctor=True, display=True)
    if doctor_msgs:
        doctor_msgs_count = doctor_msgs.count()
        total_messages = request.session.get('total_messages')
        request.session['total_messages'] = total_messages - doctor_msgs_count
        doctor_msgs.update(display=False)
    doctor_name = doctor.full_name
    messages = Message.objects.filter(patient=patient, doctor=doctor)
    context = {
        'appointments': appointments,
        'patient': patient,
        'messages': messages,
        'doctor_name': doctor_name,
        'doctor_pk': doctor_pk,
    }

    return render(request, 'patient/message.html', context)


@login_required
def doctor_list(request):
    doctors = Doctor.objects.all()
    return render(request, 'patient/doctor_list.html', {'doctor_list': doctors})

patient/templates/patient/appointment_table.html
<table class="table-bordered my-3 col-10 mx-auto" cellpadding="5">
            <thead>
              <tr class="text-center">
                <td></td>
                <td class="px-5">Doctor</td>
                <td>Status</td>
                <td>Date</td>
                <td>Time</td>
                <td>Location</td>
                <td>Token No.</td>
              </tr>
            </thead>
            <tbody>
            {% for appointment in appointments %}
            {% if appointment.status == 'Approved' %}
            <tr class="tr-close text-info text-center">
              <td><img src="{{ appointment.doctor.image.url }}" width="70px"></td>
              <td class="text-left"><u><a href="{% url 'doctor:doctor_preview' pk=appointment.doctor.pk %}">{{ appointment.doctor.full_name }}</a></u></td>
              <td>{{ appointment.status }}</td>
              <td>{{ appointment.appointment_date }}</td>
              <td>{{ appointment.appointment_time }}</td>
              <td>{{ appointment.location }}</td>
              <td>{{ appointment.token_no }}</td>
            </tr>
            {% elif appointment.status == 'Disapproved' %}
            <tr class="tr-close1">
                <td><img src="{{ appointment.doctor.image.url }}" width="70px"></td>
                <td class="text-left"><u><a href="{% url 'doctor:doctor_preview' pk=appointment.doctor.pk %}">{{ appointment.doctor.full_name }}</a></u></td>
                <td class="text-danger">Disapproved</td>
                <td colspan="4" class="text-justify text-muted p-3">
                    <a style="opacity:0.7;" href="{% url 'patient:messages' doctor_pk=appointment.doctor.pk %}" class="btn btn-outline-success btn-sm">
                        View Doctor's Message in Inbox
                    </a>
                </td>
            </tr>
            {% elif appointment.status == 'Pending' %}
            <tr class="tr-close2">
                <td><img src="{{ appointment.doctor.image.url }}" width="70px"></td>
                <td class="text-left"><u><a href="{% url 'doctor:doctor_preview' pk=appointment.doctor.pk %}">{{ appointment.doctor.full_name }}</a></u></td>
                <td class="text-danger">{{ appointment.status }}...</td>
                <td colspan="4" class="text-justify text-muted p-3">
                    <a style="opacity:0.7;" href="{% url 'patient:messages' doctor_pk=appointment.doctor.pk %}" class="btn btn-sm mt-1 btn-outline-danger">
                        Send Requested Details
                    </a>
                </td>
            </tr>
            {% endif %}
            {% endfor %}
            </tbody>
</table>

patient/templates/patient/appointments.html
{% extends 'base.html' %}

{% block content %}
<div class="container text-muted" style="opacity:0.9;">
    <a href="#" class="btn btn-primary btn-sm btn-default">Appointments</a>
    <a href="#" class="btn btn-outline-secondary btn-sm btn-new">Requested Appointments</a>
    <a href="#" class="btn btn-outline-success btn-sm btn-past">Past Appointments</a>
</div>
<hr>
<div class="col-10 text-center mx-auto mt-5">

    <div id="default" style="{% if not status == 'appointments' %}display:None{% endif %}">
    <h2 class="text-info col-5 pb-1 mx-auto">
        {% if appointments %}Your Appointments{% else %} No Appointments{% endif %}
    </h2>
    <div class="col-1 mx-auto" style="border-bottom:3px solid red;opacity:0.5;"></div>

    {% if appointments %}
    <div class="col mx-auto mt-5">
    {% include 'patient/appointment_table.html' with appointments=appointments %}
    </div>
    {% else %}
    <div class="mt-5 mx-auto">
    <a href="#" class="btn btn-secondary btn-sm my-2 btn-new">View Your Requested Appointments</a>
        <p>or</p>
        <p class="text-muted my-3">Search a a Doctor By Name Or enter some category <span class="text-success">(e.g cardialogy, gastrology)</span> </p>
    <div class="text-center mx-auto col-12">
    <form class="form-inline mt-5mt-md-0" action="{% url 'search' %}">
        <input type="hidden" name="patient_pk" value="{{ request.session.pk }}">
          <div class="col-12">
              <input style="width:280px;" class="form-control mr-sm-2" autofocus type="text" placeholder="Enter Category" name="q">
              <button class="btn btn-success text-center my-sm-0" type="submit">Search</button>
          </div>
    </form>
    </div>
    </div>
    {% endif %}
    </div>

    <div id="new" style="{% if not status == 'New' %}display:None{% endif %}">
    {% if new_appointments %}
    <h3 class="text-muted mb-5">Requested Appointments</h3>
    <div class="col-12">
    <table class="col-9 mx-auto table-bordered my-3" cellpadding="5">
            <thead>
              <tr class="text-center">
                <td></td>
                <td class="px-5">Doctor</td>
                <td>Specialization</td>
                <td>Status</td>
                <td>Date</td>
                <td>Time</td>
              </tr>
            </thead>
            <tbody>
            {% for appointment in new_appointments %}
            <tr class="tr-close text-info text-center">
              <td><img src="{{ appointment.doctor.image.url }}" width="70px"></td>
              <td class="text-left">
                  <u><a href="{% url 'doctor:doctor_preview' pk=appointment.doctor.pk %}">{{ appointment.doctor.full_name }}</a></u>
              </td>
              <td>{{ appointment.doctor.category }}</td>
              <td class="text-muted">Appointment Request Sent...</td>
              <td>{{ appointment.created.date }}</td>
              <td>{{ appointment.created.time }}</td>
            </tr>
            {% endfor %}
            </tbody>
    </table>
    </div>
    {% else %}
    <h3 class="my-3 text-muted">No Appointment Requests Sent</h3>
    <p class="text-muted my-3">Search a a Doctor By Name Or enter some category <span class="text-success">(e.g cardialogy, gastrology)</span> </p>
    <div class="text-center mx-auto col-4">
    <form class="form-inline mt-5mt-md-0" action="{% url 'search' %}">
        <input type="hidden" name="patient_pk" value="{{ request.session.pk }}">
          <input class="form-control mr-sm-2" autofocus type="text" placeholder="Enter name or Specialization" aria-label="Search" name="q">
          <button class="btn btn-success text-center my-sm-0" type="submit">Search</button>
    </form>
    </div>
    {% endif %}
    </div>

    <div id="past" style="display:none;">
    {% if past_appointments %}
    <h3 class="text-muted mb-5">Past Appointments</h3>
    <div class="col-12">
    <table class="col-9 mx-auto table-bordered my-3" cellpadding="5">
            <thead>
              <tr class="text-center">
                <td></td>
                <td class="px-5">Doctor</td>
                <td>Specialization</td>
                <td>Status</td>
                <td>Date</td>
                <td>Time</td>
                <td>Report</td>
              </tr>
            </thead>
            <tbody>
            {% for appointment in past_appointments %}
            <tr class="tr-close text-info text-center">
              <td><img src="{{ appointment.doctor.image.url }}" width="70px"></td>
              <td class="text-left">
                  <u><a href="{% url 'doctor:doctor_preview' pk=appointment.doctor.pk %}">{{ appointment.doctor.full_name }}</a></u>
              </td>
              <td>{{ appointment.doctor.category }}</td>
              <td class="text-success">Completed</td>
              <td>{{ appointment.appointment_date }}</td>
              <td>{{ appointment.appointment_time }}</td>

               <td>
                    <a class="btn btn-sm btn-outline-success" href="{{ appointment.report.url }}" target="_blank">view</a>
                    <a class="btn btn-sm btn-success ml-1" href="{% url 'doctor:download_report' ap_pk=appointment.pk %}">Download</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
    </table>
    </div>
    {% else %}
    <h3 class="my-3 text-muted">No Past Appointments</h3>
    <p class="text-muted my-3">Search a a Doctor By Name Or enter some category <span class="text-success">(e.g cardialogy, gastrology)</span> </p>
    <div class="text-center mx-auto col-4">
    <form class="form-inline mt-5mt-md-0" action="{% url 'search' %}">
        <input type="hidden" name="patient_pk" value="{{ request.session.pk }}">
          <input class="form-control mr-sm-2" autofocus type="text" placeholder="Enter Medical category" aria-label="Search" name="q">
          <button class="btn btn-success text-center my-sm-0" type="submit">Search</button>
    </form>
    </div>
    {% endif %}
    </div>

{% endblock %}

patient/templates/patient/message.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<style type="text/css" src="{% static 'css/style.css' %}"></style>

<aside id="aside" class="">
	<div class="container mt-4">

		{% for appointment in appointments %}
		<a href="{% url 'patient:messages' doctor_pk=appointment.doctor.pk %}">
		<div class="card mb-3" style="width: 22rem;">
     	 <div class="card-body">
      	<div class="row">
      		<div class="col-3">
      			<img src="{{ appointment.doctor.image.url }}" width="66px" style="border-radius: 50%;border: 2px solid silver;">
      		</div>
      		<div class="col-6 text-left mt-2">
      			<span class="text-">{{ appointment.doctor.full_name }}<br>
      	  		<span class="text-muted">{{ appointment.doctor.category }}</span>
      		</div>
      	</div>
      </div>
		</div>
		</a>
		{% endfor %}
	</div>
</aside>


<div class="chatbox bg-white">
	{% for object in messages %}
	{% if object.msg_doctor %}
	<div class="row mb-4 mt-1">
		<div class="col-6 doctor bg-dark text-info ">
			<h5 class="text-muted">{{ doctor_name }}</h5>
			<p>{{ object.msg_doctor }}</p>
			<div class="float-left" style="font: 13px courier, sans-serif; color:orange">
			<span>{{ object.created.time }}</span><br>
			<span>{{ object.created.date }}</span>
			</div>
		</div>
		<div class="col-6"></div>
	</div>
	{% endif %}
	<!-- ================================= -->
	{% if object.from_patient and object.msg_patient %}
	<div class="row mb-4">
		<div class="col-6">
		</div>
		<div class="col-6 patient bg-secondary text-white ">
			<h5 class="text-warning">You</h5>
			<p>{{ object.msg_patient }}</p>
			<div class="float-left" style="font: 13px courier, sans-serif; color:orange">
			<span>{{ object.created.time }}</span><br>
			<span>{{ object.created.date }}</span>
			</div>
			<a href="{% url 'chat:delete_msg' msg_pk=object.pk %}" class="btn btn-warning float-right btn-sm" style="opacity:0.6;">Delete</a>
		</div>
	</div>
	{% endif %}
	{% endfor %}

	{% if not messages %}
	<div class="row mb-4 mt-1">
		<div class="col-6 doctor bg-dark text-info ">
			<h5 class="text-muted">{{ first_msg.doctor.full_name }}</h5>
			<p>{{ first_msg.msg_doctor }}</p>
			<div class="float-left" style="font: 13px courier, sans-serif; color:orange">
			<span>{{ first_msg.created.time }}</span><br>
			<span>{{ first_msg.created.date }}</span>
			</div>
		</div>
		<div class="col-6"></div>
	</div>

	{% if first_msg.from_patient and first_msg.msg_patient %}
	<div class="row mb-4">
		<div class="col-6">
		</div>
		<div class="col-6 patient bg-secondary text-white ">
			<h5 class="text-warning">You</h5>
			<p>{{ first_msg.msg_patient }}</p>
			<a href="{% url 'chat:delete_msg' msg_pk=first_msg.pk %}" class="btn btn-warning float-right btn-sm" style="opacity:0.6;">Delete</a>
		</div>
	</div>
	{% endif %}
	{% endif %}

	<!-- =================  End Chat Box================ -->
</div>

	<!--=================== Text Area ==================-->
<div class="row mt-5 bg-white" style="position:fixed;bottom:15px;right:0%; width:70%;height:20%;">
	<div class="col-10">
		<form class="msg" action="{% url 'chat:create_message' %}" method="POST">{% csrf_token %}
		<textarea name="msg_patient" class="form-control" rows="5" autofocus placeholder="Enter Your Message.." style="border: 2px solid #b3b3b3;"></textarea>
	</div>
	<div class="col-2">
		<input type="hidden" name="doctor_pk" value="{{ doctor_pk }}">
		<input type="submit" value="Send" class="btn mt-2 btn-lg btn-outline-info" style="margin-left: -20px;">
	</form>
	</div>
</div>
{% endblock %}